swagger: "2.0"
info:
    title: "call_model-api"
    description: "API Gateway in front of call_model"
    version: "1.1.0"
schemes:
    - "https"
consumes:
    - "application/json"
produces:
    - "application/json"
paths:
    /call_model:
        post:
            summary: "Call Summarization Model"
            operationId: "call_model"
            x-google-backend:
                address: "https://us-central1-cloudcomputing-project-416904.cloudfunctions.net/call_model"
            responses:
                "200":
                    description: "A successful response"
                    schema: {}
security:
    - api_key: []
securityDefinitions:
    api_key:
        type: "apiKey"
        name: "key"
        in: "query"
